CREATE TABLE User (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(80) NOT NULL,
	password CHAR(41) NOT NULL
);

CREATE TABLE Post (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	usrId INTEGER(8),
	title VARCHAR(50) NOT NULL,
	description VARCHAR(250) NOT NULL
);